---
services:
  compprog-inventory-codeserver:
    image: lscr.io/linuxserver/code-server:latest
    container_name: compprog-inventory-codeserver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=p4ssw0rd
      - SUDO_PASSWORD=p4ssw0rd
      - PROXY_DOMAIN=gr4.inventory.compprog.geraldobtd.me
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      # User 1 config
      - ./config-inventory:/config

      # User 1 workspace
      - ./workspace-inventory:/config/workspace

      # General share directory
      - ./share:/host_share:ro
    expose:
      - 8443
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared_network:
    external: true

volumes:
  caddy_data_compprog:
  caddy_config_compprog:
